config/routes.rb
Rails.application.routes.draw do
  resources :listings
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "pages#home"
  get '/success', to: "payments#success", as: "payment_success"
  post '/payments/webhook', to: "payments#webhook", as: "webhook"
  post 'payments', to: "payments#create_payment_intent", as: "create_payment_intent"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :listings
end

app/models/feature.rb
class Feature < ApplicationRecord
    has_many :listings_features
    has_many :listings, through: :listings_features
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :listings_features
  has_many :features, through: :listings_features, dependent: :destroy
  accepts_nested_attributes_for :listings_features
  has_one_attached :picture

  before_save :remove_whitespace
  before_validation :convert_price_to_cents, if: :price_changed?

  private

  def remove_whitespace
    self.title = self.title.strip
    self.description = self.description.strip
  end

  def convert_price_to_cents
    self.price = (self.attributes_before_type_cast["price"].to_f * 100).round
  end

end

app/models/listings_feature.rb
class ListingsFeature < ApplicationRecord
  belongs_to :listing
  belongs_to :feature
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :listing
  belongs_to :buyer, foreign_key: 'buyer_id', class_name: "User"
  belongs_to :seller, foreign_key: 'seller_id', class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :listings
  has_many :sold_orders, class_name: "Order", foreign_key: "seller_id"
  has_many :bought_orders, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation)}
              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
         end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorise_user, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all.includes(:category)
  end

  # GET /listings/1 or /listings/1.json
  def show
    # session = Stripe::Checkout::Session.create(
    #   payment_method_types: ['card'], 
    #   customer_email: current_user&.email, #current_user && current_user.email 
    #   line_items: [{
    #     name: @listing.title, 
    #     description: @listing.description, 
    #     amount: @listing.price,
    #     currency: 'aud', 
    #     quantity: 1
    #   }], 
    #   payment_intent_data: {
    #     metadata: {
    #       user_id: current_user&.id,
    #       listing_id: @listing.id
    #     }
    #   }, 
    #   success_url: "#{root_url}/success?title=#{@listing.title}", 
    #   cancel_url: "#{root_url}/listings"
    # )

    # @session_id = session.id 
    # puts "*********"
    # pp @session_id
    # puts "*********"
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = current_user.listings.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    def authorise_user
      if current_user.id !=@listing.user_id
        flash[:error] = "You're not allowed to do that"
        redirect_to listings_path
      end
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:user_id, :category_id, :title, :description, :price, :picture, :sold, feature_ids: [])
    end

    def set_categories
      @categories = Category.all
      @features = Feature.all
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def home
    
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:webhook]

    def success
        @order = Order.find_by_listing_id(params[:id])
    end

    def create_payment_intent

        listing = Listing.find(params[:id])
        session = Stripe::Checkout::Session.create(
            payment_method_types: ['card'],
            customer_email: current_user&.email, #current_user && current_user.email
            line_items: [{
              name: listing.title,
              description: listing.description,
              amount: listing.price,
              currency: 'aud',
              quantity: 1
            }],
            payment_intent_data: {
              metadata: {
                user_id: current_user&.id,
                listing_id: listing.id
              }
            },
            success_url: "#{root_url}/success?id=#{listing.id}",
            cancel_url: "#{root_url}/listings"
          )
      
          @session_id = session.id

    end

    def webhook
        payment_id = params[:data][:object][:payment_intent]
        payment = Stripe::PaymentIntent.retrieve(payment_id)
        pp payment
        listing_id = payment.metadata.listing_id
        buyer_id = payment.metadata.user_id
        listing = Listing.find(listing_id)
        listing.update(sold: true)
        Order.create(listing_id: listing_id, buyer_id: buyer_id, seller_id: listing.user_id, payment_id: payment_id, receipt_url: payment.charges.data[0].receipt_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def select_alert_subclass(input)
        case input
        when 'notice'
            return 'info'
        when 'success'
            return 'info'
        when 'error'
            return 'danger'
        when 'alert'
            return 'warning'
        else
            return 'info'
        end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
    def image_select(listing)
        return listing.picture if listing.picture.attached?
        # use default image when no image is attached
        return "default-plant.jpg"
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardenGate</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
    <%flash.each do |key,value|%>
      <div class="alert alert-<%=select_alert_subclass(key)%> alert-dismissable fade show" role="alert">
        <%=value%>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> 
          <span aria-hidden="true"> &times; </span>
        </button>
      </div>
    <%end%>
    <%=render '/shared/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3 ml-2">
    <%= form.label :category_id, class:"form-label" %>
    <%= form.select :category_id, @categories.map {|c| [c.name, c.id]}, class:"form-select" %>
  </div>

  <div class="form-group mb-3 ml-2">
    <%= form.label :title, class:"col form-label" %>
    <%= form.text_field :title %>
  </div>

  <div class="form-group mb-3 ml-2">
    <%= form.label :description, class:"col form-label" %>
    <%= form.text_area :description %>
  </div>

  <h5 class="mb-2 ml-2"> Features </h5>

  <div class="form-check mb-3"> 
    <%=form.collection_check_boxes :feature_ids, @features, :id, :name do |b|%>
      <%=b.label class: 'form-check-label'%>
      <%=b.check_box class: 'form-check-line mr-2'%>
    <%end%>
  </div>

  <div class="form-group mb-3 ml-2">
    <%= form.label :price, class:"col form-label" %>
    <%= form.number_field :price, step: "0.01" %>
  </div>

  <div class="form-group mb-3 ml-2">
    <%= form.label :picture, class:"col form-label" %>
    <%= form.file_field :picture, class:"form-control-file", accept: "image/jpg,image/png" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Category</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.user_id %></td>
        <td><%= listing.category.name %></td>
        <td><%= listing.title %></td>
        <td><%= listing.description %></td>
        <td><%= listing.price %></td>
        <td><%= listing.sold %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div class="container d-flex flex-column flex-md-row px-2 my-2 my-md-5">

  <div class="content col-12 col-md-7 col-lg-8 p-0 pr-md-3">
    <div class="col-12 p-0 main-preview mb-4">
      <%=image_tag image_select(@listing), class: "thumbnail card-img top"%>
    </div>
  </div>

  <div class="sidebar col-lg-4 p-0 mx-2 d-md-block">
    <h1 class="mb-sm-2 mb-md-5"><%=@listing.title%></h1>
    <%@listing.features.each do |feature|%>
      <span class="badge badge-pill badge-success"><%=feature.name%></span>
    <%end%>
      <p class="blockquote my-2"><%=@listing.description%></p>

    <%if current_user && @listing.sold == false%>
      <%=button_to "Buy: $#{@listing.price / 100.0}", create_payment_intent_path, method: :post, remote: true, params:{id: @listing.id}, class: "btn btn-info p-3" %>
    <%elsif @listing.sold == true%>
      <button class="btn btn-secondary" disabled>SOLD</button>
    <%else%>
      <%=button_to "Login to buy", new_user_session_path, class: "btn btn-info"%>
    <%end%>
 

  </div>

</div>

<div class='container'>
  <div class ='d-flex justify-content-evenly'>
  <%=link_to "Edit", edit_listing_path(@listing.id), class: "btn btn-dark active mr-3" if current_user.id == @listing.user_id%>
  <%=link_to "Delete", @listing, method: :delete, data: {confirm: "Are you sure?"} , class: "btn btn-secondary active mr-3" if current_user.id == @listing.user_id%>
  </div>
</div>






  

app/views/pages/home.html.erb
<main class="landing">
    <h1>GardenGate</h1>
    <h4>Your online marketplace for buying and selling plants in your local community</h4>
</main>

app/views/payments/create_payment_intent.js.erb
const stripe = Stripe("<%=Rails.application.credentials.dig(:stripe, :public_key)%>")

stripe.redirectToCheckout({
    sessionId: "<%=@session_id%>"
});

app/views/payments/success.html.erb
<p>Thanks for purchasing! View your receipt <a href=<%=@order.receipt_url%>>here</a></p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md sticky-top navbar-dark bg-dark"> 
    <div class= "container-fluid"> 
        <%=link_to "GardenGate", root_path, class:"nav-link"%>
    </div>
    <ul class="navbar-nav mr-5-lg"> 
        <li class="nav-item">
            <%=link_to "Shop all plants", listings_path, class: "nav-link"%>
        </li>
    <% if user_signed_in? %>
        <li class="nav-item">
            <%=link_to "Create a listing", new_listing_path, class: "nav-link"%>
        </li>

        <li class="nav-item">
            <%=link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>
    <%else%>
        <li class="nav-item">
            <%=link_to "Log in", new_user_session_path, class: "nav-link"%>
        </li>

        <li class="nav-item">
            <%=link_to "Sign Up", new_user_registration_path, class: "nav-link"%>
        </li>

    <%end%>

    </ul>
    
</nav> 